const dadosEmpresas = [
    { RRRP3: 'Petróleo 3 R' },
    { EALT3: 'Aco Altona' },
    { EALT4: 'Aco Altona' },
    { ADHM3: 'Dh avançado' },
    { AERI3: 'Aeris' },
    { AESB3: 'Aes Brasil' },
    { TIET11: 'Aes Tietê E ' },
    { TIET3: 'Aes Tietê E ' },
    { TIET4: 'Aes Tietê E ' },
    { AFLT3: 'Afluente T ' },
    { BRGE11: 'Alfa Consorc ' },
    { BRGE12: 'Alfa Consorc ' },
    { BRGE3: 'Alfa Consorc ' },
    { BRGE5: 'Alfa Consorc ' },
    { BRGE6: 'Alfa Consorc ' },
    { BRGE7: 'Alfa Consorc ' },
    { BRGE8: 'Alfa Consorc ' },
    { CRIV3: 'Alfa Financ ' },
    { CRIV4: 'Alfa Financ ' },
    { RPAD3: 'Alfa Holding ' },
    { RPAD5: 'Alfa Holding ' },
    { RPAD6: 'Alfa Holding ' },
    { BRIV3: 'Alfa Invest ' },
    { BRIV4: 'Alfa Invest ' },
    { ALSO3: 'Alianscsonae ' },
    { ALZR11: 'Alianza Trust Renda Imobiliária Fundo Investimento Imobiliário ' },
    { AALR3: 'Alliar ' },
    { ALLD3: 'Aliado ' },
    { ALPA3: 'Alpargatas ' },
    { ALPA4: '   Alpargatas ' },
    { APER3: 'Alper SA ' },
    { GOGL34: 'Alfabeto DRN A ' },
    { AVLL3: 'Alphaville ' },
    { ALUP11: 'Alupar ' },
    { ALUP3: 'Alupar ' },
    { ALUP4: 'Alupar ' },
    { BAZA3: 'Amazonia ' },
    { ABEV3: 'Ambev SA ' },
    { AMBP3: 'Ambipar ' },
    { CBEE3: 'Ampla Energ ' },
    { ANIM3: 'Anima ' },
    { ARZZ3: 'Arezzo Indústria e Comércio SA ' },
    { ASAI3: 'Assai ' },
    { ATMP3: 'AtmaSA ' },
    { ATOM3: 'Atompar ' },
    { AURA33: 'Aura 360 ' },
    { AZEV3: 'Azevedo ' },
    { AZEV4: 'Azevedo ' },
    { AZUL4: 'Azul SA ' },
    { BTOW3: 'B2W - Companhia Digital ' },
    { B3SA3: 'B3 SA - Brasil, Bolsa, Balcão ' },
    { BAHI3: 'Bahema ' },
    { BMGB4: 'Banco Bmg ' },
    { BBDC3: 'Banco Bradesco SA ' },
    { BBDC4: 'Banco Bradesco SA ' },
    { BBAS3: 'Banco do Brasil SA ' },
    { BRSR6: 'Banco do Estado do Rio Grande do Sul SA ' },
    { BIDI11: 'Banco Inter ' },
    { BIDI4: 'Banco Inter SA ' },
    { BIDI3: 'Banco Inter SA ' },
    { MODL4: 'Banco Modal ' },
    { MODL11: 'Banco Modal ' },
    { MODL3: 'Banco Modal ' },
    { BPAN4: 'Banco Pan ' },
    { SANB3: 'Banco Santander (Brasil) SA ' },
    { SANB11: 'Banco Santander (Brasil) SA ' },
    { BGIP3: 'Banese ' },
    { BGIP4: 'Banese ' },
    { BEES3: 'Banestes ' },
    { BEES4: 'Banestes ' },
    { BPAR3: 'Banpara ' },
    { BRSR3: 'Banrisul ' },
    { BRSR5: 'Banrisul ' },
    { BDLL3: 'Bardella ' },
    { BDLL4: 'Bardella ' },
    { BTTL3: 'Battistella ' },
    { BALM3: 'Baumer ' },
    { BALM4: 'Baumer ' },
    { BBPO11: 'BB Progressivo II Fundo de Investimento Imobiliário - FII ' },
    { BBSE3: 'BB Seguridade Participações SA ' },
    { BMOB3: 'Bemobi Tech ' },
    { BMKS3: 'Bic Monark ' },
    { BIOM3: 'Biomm ' },
    { BSEV3: 'Biosev ' },
    { BKBR3: 'Bk Brasil ' },
    { BLAU3: 'Blau ' },
    { SOJA3: 'Boa Safra ' },
    { BOAS3: 'Boa Vista ' },
    { BOBR3: 'Bombril ' },
    { BOBR4: 'Bombril ' },
    { BBRK3: 'Corretores Br ' },
    { BRML3: 'BR Malls Participações SA ' },
    { BRPR3: 'Ir. Propert ' },
    { BRAP4: 'Bradespar SA ' },
    { BRAP3: 'Bradespar SA ' },
    { AGRO3: 'Brasilagro ' },
    { BRKM6: 'Braskem ' },
    { BRKM5: 'Braskem SA ' },
    { BRKM3: 'Braskem SA ' },
    { BSLI3: 'Brb Banco ' },
    { BSLI4: 'Brb Banco ' },
    { BRFS3: 'BRF SA ' },
    { BPAC11: 'Btgp Banco ' },
    { BPAC3: 'Btgp Banco ' },
    { BPAC5: 'Btgp Banco ' },
    { CAMB3: 'Cambuci ' },
    { CAML3: 'Camil Alimentos SA ' },
    { CRFB3: 'Carrefour Br ' },
    { CASN: 'CaSAn ' },
    { CASN3: 'CaSAn ' },
    { CASN4: 'CaSAn ' },
    { CCRO3: 'CCR SA ' },
    { CEAB3: 'Cea Modas ' },
    { CEBR3: 'Ceb ' },
    { CEBR5: 'Ceb ' },
    { CEBR6: 'Ceb ' },
    { CEDO3: 'Cedro ' },
    { CEDO4: 'Cedro ' },
    { CEED3: 'Ceee D ' },
    { CEED4: 'Ceee D ' },
    { EEEL3: 'Ceee Gt ' },
    { EEEL4: 'Ceee Gt ' },
    { CEGR3: 'Ceg ' },
    { CLSC3: 'Celesc ' },
    { CLSC4: 'Celesc ' },
    { GPAR3: 'Celgpar ' },
    { CEPE3: 'Celpe ' },
    { CEPE5: 'Celpe ' },
    { CEPE6: 'Celpe ' },
    { MAPT3: 'Cemepe ' },
    { MAPT4: 'Cemepe ' },
    { CNTO3: 'Centauro ' },
    { ELET3: 'Centrais Elétricas Brasileiras AS- Eletrobras ' },
    { ELET6: 'Centrais Elétricas Brasileiras SA - Eletrobras ' },
    { CESP3: 'Cesp ' },
    { CESP5: 'Cesp ' },
    { CESP6: 'Cesp ' },
    { HGTX3: 'Cia. Hering ' },
    { CIEL3: 'Cielo SA ' },
    { CEEB3: 'Coelba ' },
    { CEEB5: 'Coelba ' },
    { COCE3: 'Coelce ' },
    { COCE5: 'Coelce ' },
    { COGN3: 'Cogna Educação SA ' },
    { CGAS3: 'Comgas ' },
    { CGAS5: 'Comgas ' },
    { LCAM3: 'Companhia de Locação das Américas ' },
    { SBSP3: 'Companhia de Saneamento Básico do Estado de São Paulo -SABESP' },
    { CMIG3: 'Companhia Energética de Minas Gerais ' },
    { CMIG4: 'Companhia Energética de Minas Gerais ' },
    { CPLE3: 'Companhia Paranaense de Energia - COPEL ' },
    { CSNA3: 'Companhia Siderúrgica Nacional ' },
    { CALI3: 'Const A Lind ' },
    { CALI4: 'Const A Lind ' },
    { CSMG3: 'CopaSA ' },
    { CPLE5: 'Copel ' },
    { CORR4: 'Cor Ribeiro ' },
    { RLOG3: 'Log CoSAn ' },
    { CSAN3: 'Cosan SA ' },
    { CSRN3: '     Cosern ' },
    { CSRN5: 'Cosern ' },
    { CSRN6: 'Cosern ' },
    { CTNM3: 'Coteminas ' },
    { CTNM4: 'Coteminas ' },
    { CPFE3: 'CPFL Energia SA ' },
    { CRDE3: 'Cr2 ' },
    { CRPG3: 'Cristal ' },
    { CRPG5: 'Cristal ' },
    { CRPG6: 'Cristal ' },
    { CSED3: 'Cruzeiro Edu ' },
    { HGLG11: 'CSHG Logistica - Fundo De Investimento Imobiliário ' },
    { CMIN3: 'Csnmineracao ' },
    { CARD3: 'Csu Cardsyst ' },
    { CURY3: 'Cury S / A ' },
    { CVCB3: 'CVC Brasil Operadora e Agência de Viagens SA ' },
    { CCPR3: 'Cyre Com Ccp ' },
    { CYRE3: 'Cyrela Brazil Realty SA Empreendimentos e Participações ' },
    { DMVF3: 'D1000 Vfarma ' },
    { DASA3: 'DaSA ' },
    { PNVL3: 'Esmaecido ' },
    { PNVL4: 'Esmaecido ' },
    { DIRR3: 'Direcional ' },
    { DOHL3: 'Dohler ' },
    { DOHL4: 'Dohler ' },
    { DMMO3: 'Dommo ' },
    { DTCY3: 'Dtcom Direct ' },
    { DTEX3: 'Duratex ' },
    { ECOR3: 'EcoRodovias Infraestrutura e Logística SA ' },
    { ENBR3: 'EDP ​​- Energias do Brasil AS' },
    { EKTR3: 'Elektro ' },
    { EKTR4: 'Elektro ' },
    { ELET5: 'Eletrobras ' },
    { ELMD3: 'Eletromidia ' },
    { LIPR3: 'Eletropar ' },
    { EMAE3: 'Emae ' },
    { EMAE4: 'Emae ' },
    { EMBR3: 'Embraer SA ' },
    { ENAT3: 'Parte Enauta ' },
    { ECPR3: 'Encorpar ' },
    { ECPR4: 'Encorpar ' },
    { ENGI: 'EnergiSA ' },
    { ENGI11: 'EnergiSA ' },
    { ENGI3: 'EnergiSA ' },
    { ENGI4: 'EnergiSA ' },
    { ENMT3: 'EnergiSA Mt ' },
    { ENMT4: 'EnergiSA Mt ' },
    { ENEV3: 'Eneva ' },
    { EGIE3: 'Engie Brasil Energia SA ' },
    { ENJU3: 'Enjoei ' },
    { EQPA3: 'Eqtl Para ' },
    { EQPA5: 'Eqtl Para ' },
    { EQPA6: 'Eqtl Para ' },
    { EQPA7: 'Eqtl Para ' },
    { EQTL3: 'Equatorial Energia SA ' },
    { ESPA3: 'Espacolaser ' },
    { YDUQ3: 'Estácio Participações SA ' },
    { ALPK3: 'Estapar ' },
    { ESTR3: 'Estrela ' },
    { ESTR4: 'Estrela ' },
    { ETER3: 'Eternit ' },
    { EUCA3: 'Eucatex ' },
    { EUCA4: 'Eucatex ' },
    { EVEN3: 'Even ' },
    { BAUH4: 'Excelsior ' },
    { EZTC3: 'Eztec ' },
    { HTMX11: 'FD Invest Imob Hotel Maxinvest ' },
    { FHER3: 'Fer Heringer ' },
    { FESA3: 'FerbaSA ' },
    { FESA4: 'FerbaSA ' },
    { FLRY3: 'Fleury SA ' },
    { POWE3: 'Foco em ' },
    { FRAS3: 'Fras Le ' },
    { BPFF11: 'Fundo de Investimento Imobiliário - FII Brasil Plural Absoluto Fundo de Fundo' },
    { RBRP11: 'Fundo Investimento Imobiliario Rbr Properties Fii ' },
    { GFSA3: 'GafiSA ' },
    { GSHP3: 'Generalshopp ' },
    { GEPA3: 'Ger Paranap ' },
    { GEPA4: 'Ger Paranap ' },
    { GOAU3: 'Gerdau Met ' },
    { GGBR3: 'Gerdau SA ' },
    { GGBR4: 'Gerdau SA ' },
    { GOLL4: 'Gol Linhas Aéreas Inteligentes SA ' },
    { GPIV33: 'Gp Invest ' },
    { PCAR3: 'GPA Companhia Brasileira de Distribuição ' },
    { GPCP3: 'Parte Gpc ' },
    { CGRA3: 'Grazziotin ' },
    { CGRA4: 'Grazziotin ' },
    { GRND3: 'Grendene SA ' },
    { GMAT3: 'Grupo Mateus SA ' },
    { SOMA3: 'Grupo Soma ' },
    { GUAR3: 'Guararapes ' },
    { HBTS5: 'Habitasul ' },
    { HAGA3: 'Haga S / A ' },
    { HAGA4: 'Haga S / A ' },
    { HAPV3: 'Hapvida ' },
    { HBRE3: 'Hbr Realty ' },
    { HGBS11: 'HEDGE Brasil Shopping Fundo de Investimento Imobiliário ' },
    { HBOR3: 'Helbor Empreendimentos SA ' },
    { HETA3: 'Hercules ' },
    { HETA4: 'Hercules ' },
    { HBSA3: 'Hidrovias ' },
    { HOOT4: 'Hoteis Othon ' },
    { HYPE3: 'Hypera SA ' },
    { IGBR3: 'Igb S / A ' },
    { IGTA3: 'Iguatemi Empresa de Shopping Centers SA ' },
    { PARD3: 'Ihpardini ' },
    { ROMI3: 'Inds Romi ' },
    { IDVL3: 'Indusval ' },
    { IDVL4: 'Indusval ' },
    { INEP3: 'Inepar ' },
    { INEP4: 'Inepar ' },
    { IFCM3: 'Infracomm ' },
    { INTB3: 'Intelbras ' },
    { GNDI3: 'Intermedica ' },
    { MEAL3: 'International Meal Company Alimentacao SA ' },
    { MYPK3: 'Iochpe - Maxion SA ' },
    { RANI3: 'Irani ' },
    { RANI4: 'Irani ' },
    { IRBR3: 'IRB-Brasil Resseguros SA ' },
    { BOVA11: 'iShares Ibovespa Fundo de Índice ETF ' },
    { IVVB11: 'iShares S&P 500 Fundo de Investimento - Investimento No Exterior ' },
    { ITUB4: 'Itaú Unibanco Holding SA ' },
    { ITUB3: 'Itaú Unibanco Holding SA ' },
    { ITSA4: 'Itaúsa -Investimentos Itaú AS' },
    { ITSA3: 'Itausa - Investimentos Itau SA ' },
    { JBDU3: 'JB Duarte ' },
    { JBDU4: 'JB Duarte ' },
    { JALL3: 'Jallesmachad ' },
    { JBSS3: 'JBS SA ' },
    { JPSA3: 'JereisSAti ' },
    { JHSF3: 'JHSF Participações SA ' },
    { JFEN3: 'João Fortes ' },
    { JOPA3: 'JoSApar ' },
    { JOPA4: 'JoSApar ' },
    { CTKA3: 'Karsten ' },
    { CTKA4: 'Karsten ' },
    { KEPL3: 'Kepler Weber ' },
    { KNRI11: 'KINEA Renda Imobiliária -Fundo de Investimento Imobiliário ' },
    { KLBN3: 'Klabin S / A ' },
    { KLBN4: 'Klabin S / A ' },
    { KLBN11: 'KLABIN S / A UNT N2 ' },
    { LAVV3: 'Lavvi ' },
    { LLIS3: 'Le Lis Blanc ' },
    { LIGT3: 'Light S / A ' },
    { LINX3: 'Linx ' },
    { RENT3: 'Localiza Rent a Car SA ' },
    { LWSA3: 'Locaweb ' },
    { LOGG3: 'Log Com Prop ' },
    { LOGN3: 'Entrar ' },
    { LAME3: 'Lojas Americ ' },
    { LAME4: 'Lojas Americanas SA ' },
    { AMAR3: 'Lojas MariSA ' },
    { LREN3: 'Lojas Renner SA ' },
    { LPSB3: 'Lopes Brasil ' },
    { LUPA3: 'Lupatech ' },
    { MDIA3: 'M. Dias Branco SA Indústria e Comércio de Alimentos ' },
    { MGLU3: 'Magazine Luiza SA ' },
    { MGEL4: 'Mangels Indl ' },
    { POMO3: 'Marcopolo ' },
    { POMO4: 'Marcopolo ' },
    { MRFG3: 'Marfrig Global Foods SA ' },
    { MXRF11: 'Maxi Renda Fundo De Investimento Imobiliaro - FII ' },
    { MSPA3: 'Melhor Sp ' },
    { MSPA4: 'Melhor Sp ' },
    { CASH3: 'Meliuz ' },
    { MELK3: 'Melnick ' },
    { BMEB3: 'Merc Brasil ' },
    { BMEB4: 'Merc Brasil ' },
    { MERC3: 'Merc Financ ' },
    { MERC4: 'Merc Financ ' },
    { BMIN3: 'Merc Invest ' },
    { BMIN4: 'Merc Invest ' },
    { MFII11: 'Merito Desenvolvimento Imobiliário I FII -Fundo de Investimento Imobiliário ' },
    { MTIG4: 'Metal Iguaçu ' },
    { LEVE3: 'Metal Leve ' },
    { FRIO3: 'Metalfrio ' },
    { GOAU4: 'Metalurgica Gerdau SA ' },
    { MTSA3: 'MetiSA ' },
    { MTSA4: 'MetiSA ' },
    { MILS3: 'Mills Estruturas e Serviços de Engenharia SA ' },
    { BEEF: 'Minerva ' },
    { BEEF3: 'Minerva ' },
    { MNPR3: 'Minupar ' },
    { MTRE3: 'Mitre Realty ' },
    { MMXM11: 'Mmx Miner ' },
    { MMXM3: 'Mmx Miner ' },
    { MBLY3: 'Mobly ' },
    { MOAR3: 'Monte Aranha ' },
    { MOSI3: 'Mosaico ' },
    { MDNE3: 'Moura Dubeux ' },
    { MOVI3: 'Movida Participações SA ' },
    { MRVE3: 'MRV Engenharia e Participações SA ' },
    { MULT3: 'Multiplan Empreendimentos Imobiliários SA ' },
    { MNDL3: 'Mundial ' },
    { NTCO3: 'Natura & Co Holding SA ' },
    { NATU3: 'Natura Cosméticos SA ' },
    { NEOE3: 'Neoenergia ' },
    { NGRD3: 'Neogrid ' },
    { BNBR3: 'Nord Brasil ' },
    { NORD3: 'Nordon Met ' },
    { NUTR3: 'Nutriplant ' },
    { OPCT3: 'Oceanpact ' },
    { ODPV3: 'Odontoprev ' },
    { OIBR4: 'Oi ' },
    { OIBR3: 'Oi SA ' },
    { OMGE3: 'Omega Ger ' },
    { ORVR3: 'Orizon ' },
    { OSXB3: 'Osx Brasil ' },
    { OFSA3: 'Ourofino S / A ' },
    { PDTC3: 'Padtec ' },
    { PGMN3: 'Pague Menos ' },
    { PATI3: 'Panatlantica ' },
    { PATI4: 'Panatlantica ' },
    { PEAB3: 'Par Al Bahia ' },
    { PEAB4: 'Par Al Bahia ' },
    { PMAM3: 'Paranapanema ' },
    { PDGR3: 'Pdg Realt ' },
    { PETZ3: 'Pet Center Comércio e Participações SA ' },
    { RPMG3: 'Pet Manguinh ' },
    { BRDT3: 'Petrobras Distribuidora SA ' },
    { PETR4: 'Petróleo Brasileiro SA - Petrobras ' },
    { PETR3: 'Petróleo Brasileiro SA  - Petrobras ' },
    { PRIO3: 'Petrório ' },
    { PTNT3: 'Pettenati ' },
    { PTNT4: 'Pettenati ' },
    { PINE4: 'Pinho ' },
    { PLPL3: 'Planoeplano ' },
    { PLAS3: 'Peça Plascar ' },
    { FRTA3: 'Pomifrutas ' },
    { PSSA3: 'Porto Seguro SA ' },
    { PSVM11: 'Porto Vm ' },
    { PTBL3: 'Portobello ' },
    { POSI3: 'Positivo Tec ' },
    { PPLA11: 'Ppla ' },
    { PRNR3: 'Priner ' },
    { PFRM3: 'Profarma ' },
    { QUAL3: 'Qualicorp Consultoria e Corretora de Seguros SA ' },
    { LJQQ3: 'Quero Quero ' },
    { RADL3: 'Raia Drogasil SA ' },
    { RAPT3: 'Parte Randon ' },
    { RAPT4: 'Parte Randon ' },
    { RCSL3: 'Recrusul ' },
    { RCSL4: 'Recrusul ' },
    { RDOR3: 'Rede D Ou ' },
    { REDE3: 'Rede Energia ' },
    { RNEW11: 'Renova ' },
    { RNEW3: 'Renova ' },
    { RNEW4: 'Renova ' },
    { RSUL4: 'Riosulense ' },
    { RDNI3: 'Rni ' },
    { RSID3: 'Rossi Resid ' },
    { RAIL3: 'Rumo SA ' },
    { SAPR11: 'Sanepar ' },
    { SAPR3: 'Sanepar ' },
    { SAPR4: 'Sanepar ' },
    { SNSY3: 'Sansuy ' },
    { SNSY5: 'Sansuy ' },
    { SNSY6: 'Sansuy ' },
    { SANB4: 'Santander Br ' },
    { CTSA3: 'Santanense ' },
    { CTSA4: 'Santanense ' },
    { STBP3: 'Santos Brp ' },
    { SCAR3: 'São Carlos ' },
    { SMTO3: 'São Martinho ' },
    { SLED3: 'Saraiva Livr ' },
    { SLED4: 'Saraiva Livr ' },
    { SHUL4: 'Schulz ' },
    { CSAB3: 'Seg Al Bahia ' },
    { CSAB4: 'Seg Al Bahia ' },
    { SEQL3: 'Sequoia Log ' },
    { SEER3: 'Ser Educa ' },
    { SIMH3: 'Simpar ' },
    { SQIA3: 'Sinqia SA ' },
    { SLCE3: 'Slc Agricola ' },
    { SMLS3: 'Smiles Fidelidade SA ' },
    { SOND3: 'Sondotecnica ' },
    { SOND5: 'Sondotecnica ' },
    { SOND6: 'Sondotecnica ' },
    { SGPS3: 'Springs ' },
    { AHEB3: 'Spturis ' },
    { AHEB5: 'Spturis ' },
    { AHEB6: 'Spturis ' },
    { SULA11: 'Sul America ' },
    { SULA3: 'Sul America ' },
    { SULA4: 'Sul America ' },
    { SUZB3: 'Suzano SA ' },
    { TAEE3: 'TaeSA ' },
    { TAEE4: 'TaeSA ' },
    { TASA3: 'Taurus Armas ' },
    { TASA4: 'Taurus Armas SA ' },
    { TECN3: 'Technos ' },
    { TCSA3: 'Tecnisa SA ' },
    { TCNO3: 'Tecnosolo ' },
    { TCNO4: 'Tecnosolo ' },
    { TGMA3: 'Tegma ' },
    { TEKA3: 'Teka ' },
    { TEKA4: 'Teka ' },
    { TKNO4: 'Tekno ' },
    { TELB3: 'Telebras ' },
    { TELB4: 'Telebras ' },
    { VIVT3: 'Telef Brasil ' },
    { VIVT4: 'Telefônica Brasil SA ' },
    { TEND3: 'Tenda ' },
    { TESA3: 'Terra Santa ' },
    { TXRX3: 'Tex Renaux ' },
    { TIMS3: 'TIM SA ' },
    { SHOW3: 'Time For Fun ' },
    { TOTS3: 'TOTVS SA ' },
    { TFCO4: 'Track Field ' },
    { TRPL3: 'Tran Paulist ' },
    { TRPL4: 'Tran Paulist ' },
    { TAEE11: 'Transmissora Aliança de Energia Elétrica SA ' },
    { LUXM4: 'TreviSA ' },
    { TRIS3: 'Trisul ' },
    { TPIS3: 'Parte Triunfo ' },
    { TUPY3: 'Tupy ' },
    { UGPA3: 'Ultrapar Participações SA ' },
    { UCAS3: 'UnicaSA ' },
    { UNIP3: 'Unipar ' },
    { UNIP5: 'Unipar ' },
    { UNIP6: 'Unipar ' },
    { USIM3: 'Usiminas ' },
    { USIM6: 'Usiminas ' },
    { USIM5: 'Usinas Siderúrgicas de Minas Gerais SA ' },
    { VALE3: 'Vale SA ' },
    { VLID3: 'Valid Solucoes SA ' },
    { VAMO3: 'Vamos ' },
    { VVAR3: 'Via Varejo SA ' },
    { VILG11: 'Vinci Logística Fundo Investimento Imobiliário FII ' },
    { VIVA3: 'Vivara Participações SA ' },
    { VIVR3: 'Viver ' },
    { VULC3: 'Vulcabras ' },
    { WEGE3: 'WEG SA ' },
    { WEST3: 'Westwing ' },
    { MWET3: 'Wetzel S / A ' },
    { MWET4: 'Wetzel S / A ' },
    { WHRL3: 'Whirlpool ' },
    { WHRL4: 'Whirlpool ' },
    { WSON33: 'Wilson Sons ' },
    { WIZS3: 'Wiz Solucoes e Corretagem de Seguros SA ' },
    { WLMM3: 'Wlm Ind Com ' },
    { WLMM4: 'Wlm Ind Com ' }
]

export default dadosEmpresas